---
# setup Bindle

- hosts: bindle
  sudo: True
  tasks:
  - { include: playbooks/Bindle/install/roles/bindle-dependencies/tasks/main.yml, 
        user_name: ubuntu,
        bindle_git_branch: master,
        bindle_config: aws.cfg}

- hosts: bindle
  roles: 
    - { role: bindle-profiles }

- hosts: bindle
  sudo: True
  tasks:
  # this seems like the wrong place for this, but not sure what the best place for it is if we cannot redistribute 
  # with the AMI
  - name: Copy over pem key for BWA
    copy: src=/home/ubuntu/.ssh/gnostest.pem dest=/home/ubuntu/.ssh/gnostest.pem mode=600
  # change permissions
  # chamge owner
  
