---
# setup Bindle
- hosts: bindle
  vars:
    architecture_setup_path: /home/ubuntu/architecture-setup
  roles: 
    - { role: bindle-profiles }

- hosts: bindle 
  sudo: True
  roles:
    - { role: java, java_provider: Cloudera }


# Set up the architecture3 Master components locally, if *this* node is to be the Master.
# TODO: Make it configurable which node will be the Arch3 Master
- hosts: bindle
  sudo: True
  roles:
    - { role: arch3_master , tags: ['arch3_master'] } 
