---
# Add one of the following: vagrant-aws, vagrant-openstack-plugin or vagrant-vcloud
vagrant_plugin: 
vagrant_plugin_version:
# The git repo branches, if you're working in production then use the latest stable tagged version
bindle_git_branch: "master"
seqware_git_branch: "master"
pancancer-bag_git_branch: "master"
monitoring-bag_git_branch: "master"

# Add the name of the template Bindle config you will work with (e.g. "openstack.cfg")
bindle_config: 
