---

- name: Install wget
  apt: name=wget

- name: Create arch3 dir
  file: name=/home/ubuntu/{{ item }} state=directory owner=ubuntu 
  with_items:
    - arch3
    - arch3/dbsetup
    - arch3/bin
    - arch3/config
    - .youxia 

#######################
# RabbitMQ
#######################

- name: Install RabbitMQ CLI Admin
  sudo: true
  shell: wget -O - -q https://raw.githubusercontent.com/rabbitmq/rabbitmq-management/rabbitmq_v3_5_3/bin/rabbitmqadmin > /usr/local/sbin/rabbitmqadmin

#######################
# Postgres
#######################

- name: install postgres pkgs
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - postgresql-client-9.1
    - python-psycopg2

#######################
# Install Arch3 JAR
#######################

- name: Get Architecture3 jar file
  get_url: url=https://seqwaremaven.oicr.on.ca/artifactory/seqware-release/io/cancer/collaboratory/pancancer-arch-3/{{ pancancer_arch3_version }}/pancancer-arch-3-{{ pancancer_arch3_version }}.jar dest=/home/ubuntu/arch3/bin/pancancer-arch-3-{{ pancancer_arch3_version }}.jar

- name: Template masterConfig
  template: src=masterConfig.j2 dest=/home/ubuntu/arch3/config/masterConfig.json owner=ubuntu

- name: Template youxiaConfig
  template: src=youxiaConfig.j2 dest=/home/ubuntu/.youxia/config owner=ubuntu

- name: Template deployer params 
  template: src=deployer_params.j2 dest=/home/ubuntu/params.json owner=ubuntu

