---

- name: Install wget
  apt: name=wget

- name: Create arch3 dir
  file: name=/home/ubuntu/{{ item }} state=directory owner=ubuntu 
  with_items:
    - arch3
    - arch3/dbsetup
    - arch3/bin
    - arch3/config
    - .youxia 

#######################
# RabbitMQ
#######################
- name: Add RabbitMQ repo
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Add RabbitMQ key
  apt_key: url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc state=present

- name: Create rabbitmq.conf.d
  file: name=/etc/rabbitmq/rabbitmq.conf.d state=directory

- name: Copy over hostname.conf
  sudo: true
  copy: src=hostname.conf dest=/etc/rabbitmq/rabbitmq.conf.d/hostname.conf

- name: Install RabbitMQ
  apt: name=rabbitmq-server update_cache=yes force=yes

- name: Enable RabbitMQ Admin
  sudo: true
  command: rabbitmq-plugins enable rabbitmq_management

- name: Start RabbitMQ Service
  sudo: true
  service: name=rabbitmq-server state=started 

- name: Install RabbitMQ CLI Admin
  sudo: true
  shell: wget -O - -q http://localhost:15672/cli/rabbitmqadmin > /usr/local/sbin/rabbitmqadmin

- name: Add queue_user
  rabbitmq_user: user=queue_user password=queue vhost=/ configure_priv=.* read_priv=.* write_priv=.* state=present tags=administrator

#######################
# Postgres
#######################

- name: install postgres pkgs
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - postgresql-client-9.1
    - python-psycopg2

#######################
# Install Arch3 JAR
#######################

- name: Get Architecture3 jar file
  get_url: url=https://seqwaremaven.oicr.on.ca/artifactory/seqware-release/io/cancer/collaboratory/pancancer-arch-3/{{ pancancer_arch3_version }}/pancancer-arch-3-{{ pancancer_arch3_version }}.jar dest=/home/ubuntu/arch3/bin/pancancer-arch-3-{{ pancancer_arch3_version }}.jar

- name: Template masterConfig
  template: src=masterConfig.j2 dest=/home/ubuntu/arch3/config/masterConfig.json owner=ubuntu

- name: Template youxiaConfig
  template: src=youxiaConfig.j2 dest=/home/ubuntu/.youxia/config owner=ubuntu

- name: Template deployer params 
  template: src=deployer_params.j2 dest=/home/ubuntu/params.json owner=ubuntu

