---

- name: Install NTP
  sudo: True
  apt: name=ntp state=latest

- name: Start NTP on boot
  sudo: True
  service: name=ntp state=started enabled=yes


#- name: Create working dir
#  file: path=/home/{{ user_name }}/architecture2 state=directory owner={{ user_name }} group={{ user_name }}

- name: Checkout Bindle version {{ bindle_git_branch }}
  command: git checkout {{ bindle_git_branch }} creates={{ architecture_setup_path }}/Bindle_{{ bindle_git_branch }} chdir={{ architecture_setup_path }}/Bindle 

- name: Checkout workflow-decider version {{ decider_git_branch }}
  command: git checkout {{ decider_git_branch }} chdir={{ architecture_setup_path }}/workflow-decider creates={{ architecture_setup_path }}/decider_{{ decider_git_branch }}

- name: Checkout seqware-bag version {{ seqware_bag_git_branch }}
  command: git checkout {{ seqware_bag_git_branch }} chdir={{ architecture_setup_path }}/seqware-bag creates={{ architecture_setup_path }}/seqware_bag_{{ seqware_bag_git_branch }}

- name: Checkout monitoring-bag version {{ monitoring_bag_git_branch }}
  command: git checkout {{ monitoring_bag_git_branch }} chdir={{ architecture_setup_path }}/monitoring-bag creates={{ architecture_setup_path }}/monitoring_bag_{{ monitoring_bag_git_branch }}

- name: Checkout pancancer-bag version {{ pancancer_bag_git_branch }}
  command: git checkout {{ pancancer_bag_git_branch }} chdir={{ architecture_setup_path }}/pancancer-bag creates={{ architecture_setup_path }}/pancancer_bag_{{ pancancer_bag_git_branch }}

- name: get submodule statuses 
  command: chdir={{ architecture_setup_path }}
         git submodule foreach 'git status'
  register: repo_statuses

- name: display submodule statuses
  debug: var=repo_statuses.stdout_lines

