---
# If installing into a docker container, you don't need NTP you can link to the host machine's /etc/localtime
- name: Check if we're in a docker container
  stat: path=/.dockerinit
  register: dockerinit_stat

- name: Install NTP
  sudo: True
  apt: name=ntp state=latest
  when: not dockerinit_stat.stat.exists

- name: Start NTP on boot
  sudo: True
  service: name=ntp state=started enabled=yes
  when: not dockerinit_stat.stat.exists

- name: Initialize submodules
  shell: chdir={{ architecture_setup_path }}
    git submodule init

- name: Update submodules
  shell: chdir={{ architecture_setup_path }}
    git submodule update

- name: Get submodule statuses 
  command: chdir={{ architecture_setup_path }}
    git submodule foreach 'echo What is checked out? ; git describe --all'
  register: repo_statuses

- name: Display submodule statuses
  debug: var=repo_statuses.stdout_lines

- name: Copy over bash profile
  copy: src=roles/bindle-profiles/files/bashrc dest=/home/ubuntu/.bashrc owner=ubuntu

- name: Copy over service startup script
  copy: src=roles/bindle-profiles/files/start_services_in_container.sh dest=/home/ubuntu/start_services_in_container.sh owner=ubuntu mode="a+x"

- name: Copy over script that starts up workers (used for e2e integration testing)
  copy: src=roles/bindle-profiles/files/launch_workers.sh dest=/home/ubuntu/launch_workers.sh owner=ubuntu mode="a+x"

